'use client'

import { useState } from 'react'
import { ExternalLink, GitPullRequest } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useEditorStore } from '@/store/editor'
import { generateBranchName, generateDiff } from '@/lib/claude-files'
import type { CreatePRResponse } from '@/types'

export function PRModal() {
  const { isPRModalOpen, closePRModal, owner, repo, getDirtyFiles, files } = useEditorStore()

  const dirtyFiles = getDirtyFiles()
  const [branch, setBranch] = useState(() => generateBranchName('mixed'))
  const [title, setTitle] = useState('chore: update Claude Code config')
  const [isLoading, setIsLoading] = useState(false)
  const [result, setResult] = useState<CreatePRResponse | null>(null)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async () => {
    if (!branch.trim() || !title.trim()) return
    setIsLoading(true)
    setError(null)

    try {
      const payload = {
        owner,
        repo,
        branch,
        title,
        body: `## Claude Code 설정 업데이트\n\n변경된 파일:\n${dirtyFiles.map((f) => `- \`${f.path}\``).join('\n')}\n\n🤖 Generated by [clasp](https://github.com/silqwer/claudeconfig)`,
        files: dirtyFiles.map((f) => ({
          path: f.path,
          content: f.content,
          sha: f.sha || undefined,
          deleted: f.isDeleted,
        })),
      }

      const res = await fetch('/api/github/pr', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error ?? 'PR 생성 실패')
      }

      const data: CreatePRResponse = await res.json()
      setResult(data)
    } catch (e) {
      setError(e instanceof Error ? e.message : '알 수 없는 오류')
    } finally {
      setIsLoading(false)
    }
  }

  const handleClose = () => {
    if (!isLoading) {
      closePRModal()
      setResult(null)
      setError(null)
      setBranch(generateBranchName('mixed'))
      setTitle('chore: update Claude Code config')
    }
  }

  return (
    <Dialog open={isPRModalOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitPullRequest className="w-5 h-5" />
            PR 생성
          </DialogTitle>
        </DialogHeader>

        {result ? (
          <div className="flex flex-col items-center gap-4 py-6">
            <div className="w-12 h-12 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
              <GitPullRequest className="w-6 h-6 text-emerald-600 dark:text-emerald-400" />
            </div>
            <div className="text-center">
              <p className="font-semibold">PR #{result.number} 생성 완료!</p>
              <p className="text-sm text-muted-foreground mt-1">GitHub에서 확인하세요.</p>
            </div>
            <a
              href={result.url}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 rounded-lg border border-transparent bg-primary text-primary-foreground h-8 px-2.5 text-sm font-medium transition-all hover:bg-primary/80"
            >
              <ExternalLink className="w-4 h-4" />
              GitHub에서 PR 보기
            </a>
          </div>
        ) : (
          <>
            <div className="flex flex-col gap-4">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">브랜치 이름</label>
                <Input
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder="claude-config/update-rules-YYMMDD"
                  className="font-mono text-sm"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">PR 제목</label>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="chore: update Claude Code config"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-medium">
                  변경 파일{' '}
                  <Badge variant="secondary" className="ml-1">
                    {dirtyFiles.length}
                  </Badge>
                </label>
                <Tabs defaultValue="list">
                  <TabsList className="h-8">
                    <TabsTrigger value="list" className="text-xs">목록</TabsTrigger>
                    <TabsTrigger value="diff" className="text-xs">Diff</TabsTrigger>
                  </TabsList>
                  <TabsContent value="list">
                    <ScrollArea className="h-32 rounded border bg-muted/30 p-2">
                      {dirtyFiles.map((f) => (
                        <div key={f.path} className="flex items-center gap-2 py-0.5 text-xs font-mono">
                          {f.isDeleted ? (
                            <Badge variant="destructive" className="text-[10px] px-1 py-0">
                              deleted
                            </Badge>
                          ) : f.isNew ? (
                            <Badge className="text-[10px] px-1 py-0">new</Badge>
                          ) : (
                            <Badge variant="outline" className="text-[10px] px-1 py-0 text-orange-500 border-orange-500/30">
                              modified
                            </Badge>
                          )}
                          <span className="text-muted-foreground">{f.path}</span>
                        </div>
                      ))}
                    </ScrollArea>
                  </TabsContent>
                  <TabsContent value="diff">
                    <ScrollArea className="h-32 rounded border bg-muted/30">
                      <pre className="p-2 text-[10px] font-mono whitespace-pre-wrap">
                        {dirtyFiles.map((f) => {
                          const original = files.find((orig) => orig.path === f.path && !f.isNew)
                          return generateDiff(
                            original?.content ?? '',
                            f.isDeleted ? '' : f.content,
                            f.path
                          )
                        }).join('\n\n')}
                      </pre>
                    </ScrollArea>
                  </TabsContent>
                </Tabs>
              </div>

              {error && (
                <p className="text-sm text-destructive bg-destructive/10 px-3 py-2 rounded">
                  {error}
                </p>
              )}
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={handleClose} disabled={isLoading}>
                취소
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={isLoading || !branch.trim() || !title.trim() || dirtyFiles.length === 0}
                className="gap-2"
              >
                <GitPullRequest className="w-4 h-4" />
                {isLoading ? 'PR 생성 중...' : 'PR 생성'}
              </Button>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}
